services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - proton-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankproton
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proton-network

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - '8161:8161'
      - '61616:61616'
    networks:
      - proton-network

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankproton
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - proton-network

networks:
  proton-network:
    driver: bridge

volumes:
  mysql_data:
