spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin


  application:
    name: JavaSpring

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/bankproton}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path:


jwt:
  secretKey: 95eb8e8ad97cee6d9829f420e93187c2e98808deaa5bd9e5a660a6d8f9d78af9
